import { scrapeGeneratorWithJsdom } from '../playwright/scraper.js';
import { validatePerchance } from '../core/validator.js';
import { previewRolls } from '../core/exporter.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import http from 'http';
import type { IncomingMessage, ServerResponse } from 'http';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function sendJson(res: ServerResponse, status: number, data: unknown) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}

function sendFile(res: ServerResponse, filePath: string, contentType: string) {
  const content = fs.readFileSync(filePath, 'utf-8');
  res.writeHead(200, { 'Content-Type': contentType });
  res.end(content);
}

function getBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', chunk => (body += chunk));
    req.on('end', () => resolve(body));
    req.on('error', reject);
  });
}

export function createUiServer(port = 3000): Promise<void> {
  return new Promise((resolve, reject) => {
    const server = http.createServer(async (req: IncomingMessage, res: ServerResponse) => {
      const url = new URL(req.url || '/', `http://localhost:${port}`);

      // Serve the web UI
      if (url.pathname === '/' || url.pathname === '/index.html') {
        sendFile(res, path.join(__dirname, 'index.html'), 'text/html; charset=utf-8');
        return;
      }

      // Scrape endpoint — uses jsdom (no browser needed)
      if (url.pathname === '/api/scrape') {
        const generatorUrl = url.searchParams.get('url');
        if (!generatorUrl) {
          sendJson(res, 400, { error: 'Missing url parameter' });
          return;
        }

        try {
          const scraped = await scrapeGeneratorWithJsdom(generatorUrl);
          const validation = validatePerchance(scraped.code);
          const preview = previewRolls(scraped.code, 8);

          sendJson(res, 200, {
            success: true,
            url: scraped.url,
            name: scraped.name,
            code: scraped.code,
            description: scraped.description,
            scrapedAt: scraped.scrapedAt,
            validation: {
              valid: validation.valid,
              stats: validation.stats,
            },
            preview,
            previewCount: preview.length,
          });
        } catch (err: any) {
          sendJson(res, 500, { success: false, error: err.message });
        }
        return;
      }

      // Preview endpoint — local roll preview
      if (url.pathname === '/api/preview' && req.method === 'POST') {
        const body = JSON.parse(await getBody(req));
        const code = body.code || '';
        const count = body.count || 8;
        const rolls = previewRolls(code, count);
        const validation = validatePerchance(code);
        sendJson(res, 200, {
          rolls,
          validation: {
            valid: validation.valid,
            stats: validation.stats,
          },
        });
        return;
      }

      // Validate endpoint
      if (url.pathname === '/api/validate' && req.method === 'POST') {
        const body = JSON.parse(await getBody(req));
        const code = body.code || '';
        const result = validatePerchance(code);
        sendJson(res, 200, result);
        return;
      }

      // Download endpoint
      if (url.pathname === '/api/download' && req.method === 'POST') {
        const body = JSON.parse(await getBody(req));
        const code = body.code || '';
        const filename = body.filename || 'generator.perchance';
        const header = `// Generated by Perchance AI Toolkit\n// https://github.com/Gzeu/perchance-ai-prompt-library\n// Paste this at https://perchance.org/minimal#edit\n\n`;
        res.writeHead(200, {
          'Content-Type': 'text/plain',
          'Content-Disposition': `attachment; filename="${filename}"`,
        });
        res.end(header + code);
        return;
      }

      // Not found
      sendJson(res, 404, { error: 'Not found. Try /' });
    });

    server.listen(port, () => {
      console.log(`\n🎲 Perchance UI  —  http://localhost:${port}`);
      console.log('Scrape perchance.org generators in your browser, no browser needed.');
      resolve();
    });

    server.on('error', reject);
  });
}
