/**
 * Export .perchance files and copy to clipboard
 */
import fs from 'fs';
import path from 'path';

export interface ExportOptions {
  filename?: string;
  outputDir?: string;
  clipboard?: boolean;
  addHeader?: boolean;
}

export async function exportGenerator(
  code: string,
  options: ExportOptions = {}
): Promise<{ filepath?: string; copied: boolean }> {
  const {
    filename = `generator-${Date.now()}.perchance`,
    outputDir = './output',
    clipboard = false,
    addHeader = true
  } = options;

  let finalCode = code;
  if (addHeader) {
    finalCode = `// Generated by Perchance AI Toolkit\n// https://github.com/Gzeu/perchance-ai-prompt-library\n// Paste this at https://perchance.org/minimal#edit\n\n${code}`;
  }

  let filepath: string | undefined;

  if (outputDir) {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    filepath = path.join(outputDir, filename);
    fs.writeFileSync(filepath, finalCode, 'utf-8');
  }

  let copied = false;
  if (clipboard) {
    try {
      const { default: clipboardy } = await import('clipboardy');
      await clipboardy.write(finalCode);
      copied = true;
    } catch {
      // clipboard not available in headless
    }
  }

  return { filepath, copied };
}

export function previewRolls(code: string, count = 5): string[] {
  // Simple local roll preview without browser
  const lists: Record<string, string[]> = {};
  let currentList = '';

  for (const line of code.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('import')) continue;

    if (!line.startsWith(' ') && !line.startsWith('\t')) {
      currentList = trimmed;
      lists[currentList] = [];
    } else if (currentList) {
      const value = trimmed.replace(/\^\d+(\.\d+)?/, '').replace(/\/\/.*$/, '').trim();
      if (value) lists[currentList].push(value);
    }
  }

  const outputList = lists['output'] || lists['generate'] || Object.values(lists)[0] || [];
  if (!outputList.length) return ['(no output list found)'];

  // Unicode-aware reference matcher (handles diacritics like ă î ș ț).
  const refRegex = /\[([\p{L}\p{N}_]+)\]/gu;

  // Resolve [references], recursing so nested references expand too.
  const resolve = (template: string): string => {
    let result = template;
    for (let depth = 0; depth < 12; depth++) {
      const next = result.replace(refRegex, (_m, ref: string) => {
        const refList = lists[ref] || [];
        return refList.length
          ? refList[Math.floor(Math.random() * refList.length)]
          : `[${ref}]`;
      });
      if (next === result) break;
      result = next;
    }
    return result;
  };

  const results: string[] = [];
  for (let i = 0; i < count; i++) {
    const template = outputList[Math.floor(Math.random() * outputList.length)];
    results.push(resolve(template));
  }
  return results;
}
