import * as fs from 'fs';
import * as path from 'path';
import type { Agent, GeneratedVariant, AgenticSessionResult, SelectedAgentSummary } from '../types/agentic';
import {
  AGENT_REGISTRY,
  selectAgentsForRequest,
  getAgentById,
  toAgentSummary,
  type AgentDefinition
} from './registry';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const groq = require('../services/groqService.js') as {
  SYSTEM_PROMPT: string;
  FAST_MODEL: string;
  callGroq: (
    messages: { role: string; content: string }[],
    maxTokens?: number,
    model?: string
  ) => Promise<string>;
  cleanCode: (raw: string) => string;
  isGroqConfigured: () => boolean;
};

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { validateCode } = require('../utils/perchanceValidate.js') as {
  validateCode: (code: string) => { valid: boolean; errors: string[]; warnings: string[] };
};

const COMPLEXITY_HINTS: Record<string, string> = {
  simple: 'Create a simple generator with 3-5 lists, 8-12 items each.',
  medium: 'Create a medium generator with 5-8 lists, 10-15 items each. Use nested references.',
  master:
    'Create a MASTER generator with 8-12 lists, 15-20 items each. Production-ready with rich variety.'
};

export interface BrainstormOptions {
  category?: string;
  iterations?: number;
  complexity?: string;
  theme?: string;
}

export class UltraAgenticOrchestrator {
  private memory = new Map<string, GeneratedVariant>();
  private memoryDir: string;

  constructor(memoryDir?: string) {
    this.memoryDir = memoryDir || path.join(process.cwd(), '.perchance-agentic-memory');
    this.loadMemoryFromDisk();
  }

  async brainstorm(
    prompt: string,
    options: BrainstormOptions = {}
  ): Promise<AgenticSessionResult> {
    if (!groq.isGroqConfigured()) {
      throw Object.assign(new Error('GROQ_API_KEY not configured'), { status: 503 });
    }

    const {
      category = 'writing',
      iterations = 2,
      complexity = 'medium',
      theme
    } = options;

    const t0 = Date.now();
    const selectedAgents = selectAgentsForRequest(prompt, category);
    const selectedSummaries: SelectedAgentSummary[] = selectedAgents.map(toAgentSummary);
    const complexityHint = COMPLEXITY_HINTS[complexity] || COMPLEXITY_HINTS.medium;
    const memoryHint = this.getMemoryContext(prompt);

    let variants = await this.generateInitialVariants(
      selectedAgents,
      prompt,
      category,
      complexityHint,
      theme,
      memoryHint
    );

    const debateRounds = Math.min(Math.max(iterations, 1), 3);
    for (let i = 0; i < debateRounds; i++) {
      await this.runDebateRound(variants, selectedAgents);
      variants = await this.weightedVoting(variants);
    }

    let best = variants[0];
    if (!best) {
      throw new Error('No variants generated by agentic pipeline');
    }

    const syntaxMaster = getAgentById('syntax-master');
    if (syntaxMaster) {
      best = await this.refineWithAgent(best, syntaxMaster, prompt, 'Polish syntax and fix any Perchance issues.');
    }

    const validation = validateCode(best.content);
    const syntaxBonus = validation.valid ? 0.5 : -1;
    best.score = Math.min(10, best.score + syntaxBonus);

    this.saveToMemory(prompt, best);

    return {
      prompt,
      bestVariant: best,
      allVariants: variants,
      agentsUsed: selectedAgents.map((a) => a.name),
      selectedAgents: selectedSummaries,
      memoryUsed: memoryHint.length > 0,
      finalScore: best.score,
      code: best.content,
      validation,
      debateRounds,
      generationTime: Date.now() - t0,
      category,
      complexity
    };
  }

  private buildUserMessage(
    agent: AgentDefinition,
    prompt: string,
    category: string,
    complexityHint: string,
    theme?: string,
    memoryHint?: string
  ): string {
    return [
      `You are ${agent.name}, a specialized Perchance generator expert.`,
      agent.systemPromptFragment,
      '',
      `Category: ${category}`,
      `User request: ${prompt}`,
      theme ? `Theme: ${theme}` : '',
      complexityHint,
      memoryHint || '',
      '',
      'Generate complete Perchance code for this request.'
    ]
      .filter(Boolean)
      .join('\n');
  }

  private getMemoryContext(prompt: string): string {
    const words = prompt
      .toLowerCase()
      .split(/\W+/)
      .filter((w) => w.length > 3);
    if (words.length === 0 || this.memory.size === 0) return '';

    let bestKey: string | null = null;
    let bestVariant: GeneratedVariant | null = null;
    let bestOverlap = 0;

    for (const [key, variant] of this.memory) {
      const keyWords = key.toLowerCase().split(/\W+/);
      const overlap = words.filter((w) =>
        keyWords.some((kw) => kw.includes(w) || w.includes(kw))
      ).length;
      if (overlap > bestOverlap) {
        bestOverlap = overlap;
        bestKey = key;
        bestVariant = variant;
      }
    }

    if (!bestKey || !bestVariant || bestOverlap === 0) return '';

    const snippet = bestVariant.content.slice(0, 700);
    return [
      'Relevant prior successful generator (use as structural inspiration, do not copy verbatim):',
      snippet,
      bestVariant.content.length > 700 ? '...(truncated)' : ''
    ].join('\n');
  }

  private async generateInitialVariants(
    agents: AgentDefinition[],
    prompt: string,
    category: string,
    complexityHint: string,
    theme?: string,
    memoryHint?: string
  ): Promise<GeneratedVariant[]> {
    const maxTokens = complexityHint.includes('MASTER') ? 4096 : 2048;

    const results = await Promise.all(
      agents.map((agent, index) =>
        this.generateVariantForAgent(
          agent,
          index,
          prompt,
          category,
          complexityHint,
          theme,
          memoryHint,
          maxTokens
        )
      )
    );

    return results.sort((a, b) => b.score - a.score);
  }

  private async generateVariantForAgent(
    agent: AgentDefinition,
    index: number,
    prompt: string,
    category: string,
    complexityHint: string,
    theme: string | undefined,
    memoryHint: string | undefined,
    maxTokens: number
  ): Promise<GeneratedVariant> {
    const userMsg = this.buildUserMessage(agent, prompt, category, complexityHint, theme, memoryHint);
    const raw = await groq.callGroq(
      [
        { role: 'system', content: groq.SYSTEM_PROMPT },
        { role: 'user', content: userMsg }
      ],
      maxTokens
    );
    const content = groq.cleanCode(raw);
    const validation = validateCode(content);
    const skillAvg =
      agent.skills.reduce((sum, s) => sum + s.score, 0) / Math.max(agent.skills.length, 1);
    const score = skillAvg / 10 + (validation.valid ? 0.5 : 0);

    return {
      id: `var-${index}`,
      content,
      score,
      agent: agent.name,
      skillsUsed: agent.skills
    };
  }

  private async runDebateRound(variants: GeneratedVariant[], agents: Agent[]) {
    const top = variants.slice(0, 2);
    if (top.length === 0) return;

    await Promise.all(
      top.flatMap((variant) =>
        agents.map(async (agent) => {
          try {
            const raw = await groq.callGroq(
              [
                {
                  role: 'system',
                  content:
                    'Critique Perchance generator code. Reply ONLY with JSON: {"score":1-10,"issues":[],"suggestion":""}'
                },
                {
                  role: 'user',
                  content: `Agent ${agent.name} reviews this code:\n\n${variant.content}\n\nScore 1-10 for quality, syntax, and fit.`
                }
              ],
              300,
              groq.FAST_MODEL
            );
            const match = raw.match(/\{[\s\S]*\}/);
            if (match) {
              const critique = JSON.parse(match[0]) as { score?: number };
              if (typeof critique.score === 'number') {
                variant.score = (variant.score + critique.score) / 2;
              }
            }
          } catch {
            // Debate round is best-effort
          }
        })
      )
    );
  }

  private async weightedVoting(variants: GeneratedVariant[]): Promise<GeneratedVariant[]> {
    return [...variants].sort((a, b) => {
      const aVal = validateCode(a.content);
      const bVal = validateCode(b.content);
      const aBonus = aVal.valid ? 0.3 : 0;
      const bBonus = bVal.valid ? 0.3 : 0;
      return b.score + bBonus - (a.score + aBonus);
    });
  }

  private async refineWithAgent(
    variant: GeneratedVariant,
    agent: AgentDefinition,
    prompt: string,
    instruction: string
  ): Promise<GeneratedVariant> {
    const raw = await groq.callGroq([
      { role: 'system', content: groq.SYSTEM_PROMPT },
      {
        role: 'user',
        content: [
          `${agent.name}: ${agent.systemPromptFragment}`,
          `Original request: ${prompt}`,
          instruction,
          '',
          'Existing code:',
          variant.content,
          '',
          'Output only the improved Perchance code:'
        ].join('\n')
      }
    ]);
    const content = groq.cleanCode(raw);
    const validation = validateCode(content);
    return {
      ...variant,
      content,
      score: variant.score + (validation.valid ? 0.4 : 0),
      agent: `${variant.agent}+${agent.name}`
    };
  }

  private loadMemoryFromDisk() {
    try {
      if (!fs.existsSync(this.memoryDir)) return;
      const files = fs.readdirSync(this.memoryDir).filter((f) => f.endsWith('.json'));
      for (const file of files.slice(-50)) {
        const data = JSON.parse(fs.readFileSync(path.join(this.memoryDir, file), 'utf8')) as {
          key: string;
          variant: GeneratedVariant;
        };
        if (data.key && data.variant) this.memory.set(data.key, data.variant);
      }
    } catch {
      // Memory load is optional
    }
  }

  private saveToMemory(key: string, data: GeneratedVariant) {
    this.memory.set(key, data);
    try {
      if (!fs.existsSync(this.memoryDir)) {
        fs.mkdirSync(this.memoryDir, { recursive: true });
      }
      const slug = key.slice(0, 40).replace(/[^a-z0-9]+/gi, '-').toLowerCase();
      const file = path.join(this.memoryDir, `${Date.now()}-${slug}.json`);
      fs.writeFileSync(file, JSON.stringify({ key, variant: data, savedAt: new Date().toISOString() }, null, 2));
    } catch {
      // Silent fail for memory persistence
    }
  }

  getAgentsStatus() {
    return {
      totalAgents: AGENT_REGISTRY.length,
      agents: AGENT_REGISTRY.map(({ id, name, bio, skills, expertise }) => ({
        id,
        name,
        bio,
        skills,
        expertise
      })),
      memoryEntries: this.memory.size,
      groqConfigured: groq.isGroqConfigured()
    };
  }
}

export const orchestrator = new UltraAgenticOrchestrator();
