name: Lockfile Autofix

# This workflow automatically fixes lockfile issues by regenerating package-lock.json
# It runs on a schedule and can also be triggered manually or on workflow_dispatch

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
    inputs:
      force_regenerate:
        description: 'Force regenerate lockfile even if no issues detected'
        required: false
        default: 'false'
        type: boolean
  
  # Run weekly to catch drift issues
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC
  
  # Also run when CI fails due to lockfile issues
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  fix-lockfile:
    name: Fix Package Lock Issues
    runs-on: ubuntu-latest
    
    # Only run if CI failed or if manually triggered
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Check if lockfile fix is needed
      id: check-lockfile
      run: |
        echo "Checking if lockfile needs fixing..."
        
        # Try npm ci first to see if there are issues
        if npm ci > /dev/null 2>&1; then
          echo "Lockfile appears to be valid"
          if [ "${{ github.event.inputs.force_regenerate }}" = "true" ]; then
            echo "Force regenerate requested"
            echo "needs_fix=true" >> $GITHUB_OUTPUT
          else
            echo "needs_fix=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "Lockfile has issues, needs regeneration"
          echo "needs_fix=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Backup current lockfile
      if: steps.check-lockfile.outputs.needs_fix == 'true'
      run: |
        if [ -f package-lock.json ]; then
          cp package-lock.json package-lock.json.backup
          echo "Backed up existing lockfile"
        fi
    
    - name: Remove node_modules and lockfile
      if: steps.check-lockfile.outputs.needs_fix == 'true'
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        echo "Cleaned up node_modules and lockfile"
    
    - name: Regenerate lockfile
      if: steps.check-lockfile.outputs.needs_fix == 'true'
      run: |
        echo "Regenerating package-lock.json..."
        npm install
        echo "Successfully regenerated lockfile"
    
    - name: Verify new lockfile works
      if: steps.check-lockfile.outputs.needs_fix == 'true'
      run: |
        echo "Verifying new lockfile..."
        rm -rf node_modules
        npm ci
        echo "New lockfile verified successfully"
    
    - name: Check for changes
      if: steps.check-lockfile.outputs.needs_fix == 'true'
      id: git-check
      run: |
        git diff --exit-code package-lock.json > /dev/null
        if [ $? -eq 0 ]; then
          echo "No changes in lockfile"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Lockfile has been updated"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check-lockfile.outputs.needs_fix == 'true' && steps.git-check.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package-lock.json
        git commit -m "fix: regenerate package-lock.json to resolve lockfile issues
        
        - Automatically regenerated lockfile due to synchronization issues
        - This should resolve npm ci failures in CI/CD pipeline
        - Generated by lockfile-autofix workflow"
        git push
    
    - name: Create Issue on Failure
      if: failure()
      uses: actions/github-script@v8
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🔧 Lockfile Autofix Failed',
            body: `## Lockfile Autofix Failed
          
          The automated lockfile regeneration workflow failed. This may indicate:
          
          - **Package conflicts**: Dependencies may have incompatible version requirements
          - **Registry issues**: npm registry may be experiencing problems  
          - **Package.json issues**: There may be syntax errors or invalid dependencies
          
          ### Recommended Actions:
          
          1. Check the [workflow run logs](${context.payload.repository.html_url}/actions/runs/${context.runId}) for specific error details
          2. Manually run \`npm install\` locally to identify the issue
          3. Review recent changes to package.json
          4. Consider updating or removing problematic dependencies
          
          ### Manual Fix:
          
          \`\`\`bash
          # Clean install to regenerate lockfile
          rm -rf node_modules package-lock.json
          npm install
          git add package-lock.json
          git commit -m "fix: manually regenerate lockfile"
          git push
          \`\`\`
          
          ---
          *This issue was automatically created by the lockfile-autofix workflow.*`,
            labels: ['bug', 'dependencies', 'automation']
          })
    
    - name: Report Success
      if: steps.check-lockfile.outputs.needs_fix == 'true' && steps.git-check.outputs.has_changes == 'true'
      run: |
        echo "✅ Lockfile successfully regenerated and committed!"
        echo "The CI/CD pipeline should now pass on the next run."
    
    - name: Report No Changes Needed
      if: steps.check-lockfile.outputs.needs_fix == 'false'
      run: |
        echo "✅ Lockfile is already in sync, no changes needed."
